### PR TITLE
update for new version of bluesky-kafka

### PR DESCRIPTION
**Pull request by jklynch**

### CODE REVIEW

**Review by mrakitin — COMMENTED** [review]
Should it have a version change? Did you intend to replace `kafka-python` with something else?

**Comment by jklynch** [comment]
The version of this package will have to change, I assume to 0.2? The bluesky_kafka package will be released at version 0.1.0. The kafka-python dependency will be replaced with confluent-kafka.

**Comment by mrakitin** [comment]
Power-cycled this PR to trigger the CI builds.

**Comment by mrakitin** [comment]
It was taken care of by https://github.com/nsls-ii-forge/bluesky-kafka-feedstock/pull/4 earlier. Closing as duplicate.

**Pull request closed without merging**
